server:
  port: 9092
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.40.1:3306/1907aaaaa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    #热部署生效
  devtools:
    restart:
      enabled: true

  freemarker:
    cache: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  mvc:
    static-path-pattern: /**
    view:
      prefix:
  messages:
    basename: static/message/messages   #配置国际化语言
  redis:
    host:
    port: 6379
    jedis:
      pool:
        max-idle:
        min-idle: 1
        max-active: 1000


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fh.shopportal.logon.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #第2中日志打印

